<a href="https://colab.research.google.com/github/simranchoudhary2907/Activity/blob/main/Practice_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practice Assignment 1

In [3]:
import numpy as np

arr = np.random.randint(5,21, size=(3,3))
print("Array:\n",arr)

row_means = np.mean(arr,axis=1)
print("Row Means:\n",row_means)

Array:
 [[16  5 12]
 [19 12 16]
 [17 12 11]]
Row Means:
 [11.         15.66666667 13.33333333]


In [7]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie","E"],
    "Score": [75,45,60,30]
}

df = pd.DataFrame(data)

filtered_df = df[df["Score"] >= 60]
print(filtered_df)


      Name  Score
0    Alice     75
2  Charlie     60


In [8]:
def normalize(list):
  min_val = min(list)
  max_val = max(list)

  normalized = [(x-min_val)/(max_val - min_val) for x in list]
  return normalized

print(normalize([10,20,30,40]))

[0.0, 0.3333333333333333, 0.6666666666666666, 1.0]


In [9]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

result = np.dot(A,B)
print(result)

[[19 22]
 [43 50]]


In [10]:
import pandas as pd
df = pd.read_csv("/content/heart - heart.csv")
print(df)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [11]:
print(df.shape)

(303, 14)


In [16]:
print(df.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
298    0
299    0
300    0
301    0
302    0
Length: 303, dtype: int64


In [17]:
print(df.dtypes)

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object


In [19]:
print(df["age"].mean())

54.366336633663366


In [20]:
from sklearn.model_selection import train_test_split

selected = df[["age","sex","cp","restecg","chol"]]

train,test = train_test_split(selected,test_size=0.25,random_state=42)

print("Tarining Data:\n",train)
print("Testing Data:\n",test)

Tarining Data:
      age  sex  cp  restecg  chol
287   57    1   1        0   232
282   59    1   2        1   218
197   67    1   0        1   254
158   58    1   1        1   220
164   38    1   2        1   175
..   ...  ...  ..      ...   ...
188   50    1   2        1   233
71    51    1   2        1   227
106   69    1   3        0   234
270   46    1   0        0   249
102   63    0   1        1   195

[227 rows x 5 columns]
Testing Data:
      age  sex  cp  restecg  chol
179   57    1   0        0   276
228   59    1   3        0   288
111   57    1   2        1   126
246   56    0   0        0   409
60    71    0   2        0   265
..   ...  ...  ..      ...   ...
22    42    1   0        1   226
258   62    0   0        1   244
56    48    1   0        0   222
242   64    1   0        0   212
114   55    1   1        1   262

[76 rows x 5 columns]
